# Generated by Django 4.2.5 on 2023-09-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=10, verbose_name='Team Name')),
                ('david', models.CharField(max_length=20, verbose_name='David')),
                ('nick', models.CharField(max_length=20, verbose_name='Nick')),
                ('neil', models.CharField(max_length=20, verbose_name='Neil')),
                ('dhruvisha', models.CharField(max_length=20, verbose_name='Dhruvisha')),
                ('ryan', models.CharField(max_length=20, verbose_name='Ryan')),
                ('version', models.IntegerField()),
                ('release_date', models.DateTimeField(verbose_name='Release Date')),
                ('product_name', models.CharField(max_length=20, verbose_name='Team Name')),
                ('description', models.TextField()),
            ],
        ),
    ]
