# Generated by Django 4.2.5 on 2023-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='product_name',
            field=models.CharField(max_length=20, verbose_name='Product Name'),
        ),
    ]
