# Generated by Django 4.2.5 on 2023-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='david',
            field=models.CharField(max_length=20, verbose_name="David's Name"),
        ),
        migrations.AlterField(
            model_name='about',
            name='dhruvisha',
            field=models.CharField(max_length=20, verbose_name="Dhruvisha's Name"),
        ),
        migrations.AlterField(
            model_name='about',
            name='neil',
            field=models.CharField(max_length=20, verbose_name="Neil's Name"),
        ),
        migrations.AlterField(
            model_name='about',
            name='nick',
            field=models.CharField(max_length=20, verbose_name="Nick's Name"),
        ),
        migrations.AlterField(
            model_name='about',
            name='release_date',
            field=models.DateField(verbose_name='Release Date'),
        ),
        migrations.AlterField(
            model_name='about',
            name='ryan',
            field=models.CharField(max_length=20, verbose_name="Ryan's Name"),
        ),
    ]
