# Generated by Django 4.2.5 on 2023-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_david_alter_about_dhruvisha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Sprint Number:'),
        ),
    ]
