# Generated by Django 4.2.5 on 2023-12-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_product_description_product_genre_product_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
