# Generated by Django 4.2.5 on 2023-10-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('email', models.EmailField(blank=True, max_length=75)),
                ('is_driver', models.BooleanField(default=False, verbose_name='driver status')),
                ('is_sponsor', models.BooleanField(default=False, verbose_name='sponsor status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.userprofile')),
                ('street_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('drivers_license', models.CharField(blank=True, max_length=15)),
                ('year', models.PositiveIntegerField(null=True)),
                ('make', models.CharField(blank=True, max_length=25)),
                ('model', models.CharField(blank=True, max_length=25)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('policy_number', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
            ],
            bases=('members.userprofile',),
        ),
    ]
