# Generated by Django 4.2.5 on 2023-10-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=85),
        ),
    ]
