# Generated by Django 4.2.5 on 2023-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
