# Generated by Django 4.2.5 on 2023-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_userprofile_sponsor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sponsor_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sponsor_name',
            field=models.ManyToManyField(related_name='sponsored_users', to='members.sponsorlist'),
        ),
    ]
