# Generated by Django 4.2.5 on 2023-11-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_sponsorlist_remove_userprofile_sponsor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sponsor_name',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_users', to='members.sponsorlist'),
        ),
        migrations.AlterField(
            model_name='sponsorlist',
            name='sponsor_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='SponsorUserProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.userprofile')),
                ('sponsor_name', models.CharField(max_length=25, unique=True)),
            ],
            bases=('members.userprofile',),
        ),
    ]
