# Generated by Django 4.2.5 on 2023-11-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_sponsoruserprofile_sponsor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorlist',
            name='point_conversion',
            field=models.FloatField(default=0.01),
        ),
    ]
