# Generated by Django 4.2.6 on 2023-10-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datestamp', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(default='test', max_length=150)),
                ('login_success', models.BooleanField()),
            ],
        ),
    ]
