# Generated by Django 4.2.5 on 2023-10-31 14:19

import application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('email', models.EmailField(max_length=75)),
                ('phone', models.CharField(max_length=10, validators=[application.models.validate_phone_number, django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits long.', regex='^\\d{10}$')])),
                ('street_address', models.CharField(max_length=85)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=5)),
                ('license_num', models.CharField(max_length=30)),
                ('plate_num', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('make', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('vin', models.CharField(max_length=17)),
                ('provider_name', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=50)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.driverprofile')),
            ],
        ),
    ]
