# Generated by Django 4.2.5 on 2023-10-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='approval status'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='application status'),
        ),
    ]
