# Generated by Django 4.2.5 on 2023-11-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_reason',
            field=models.TextField(default='Enter reason for your decision.', max_length=250),
        ),
    ]
