# Generated by Django 4.2.5 on 2023-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_application_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_waitlisted',
            field=models.BooleanField(default=False, verbose_name='waitlist status'),
        ),
    ]
